import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';

export default defineConfig({
  build: {
    minify: false,
    sourcemap: true,
    lib: {
      entry: {
        index: 'src/index.ts',
        browser: 'src/browser.ts',
        'gas/index': 'src/gas/index.ts',
        // New server entry point
        server: 'src/server/index.ts',
        // Auth strategies under server namespace
        'server/auth/firebase': 'src/auth/strategies/firebase.ts',
        'server/auth/memory': 'src/auth/strategies/memory.ts',
        'server/auth/rbac': 'src/auth/strategies/rbac.ts',
        // MCP
        mcp: 'src/mcp/index.ts',
        'mcp/cli': 'src/mcp/cli.ts',
      },
      name: 'modjules',
      formats: ['es'],
      fileName: (format, entryName) => `${entryName}.mjs`,
    },
    rollupOptions: {
      external: [
        // Runtime dependencies (keep bundled for Node, external for Browser if provided by platform)
        'idb',
        'firebase-admin',
        /@modelcontextprotocol\/sdk(\/.*)?/,
        'commander',
        'chalk',
        /@inquirer\/prompts(\/.*)?/,

        // Node.js Built-ins (Bare specifiers)
        '_http_agent',
        '_http_client',
        '_http_common',
        '_http_incoming',
        '_http_outgoing',
        '_http_server',
        '_stream_duplex',
        '_stream_passthrough',
        '_stream_readable',
        '_stream_transform',
        '_stream_wrap',
        '_stream_writable',
        '_tls_common',
        '_tls_wrap',
        'assert',
        'assert/strict',
        'async_hooks',
        'buffer',
        'child_process',
        'cluster',
        'console',
        'constants',
        'crypto',
        'dgram',
        'diagnostics_channel',
        'dns',
        'dns/promises',
        'domain',
        'events',
        'fs',
        'fs/promises',
        'http',
        'http2',
        'https',
        'inspector',
        'inspector/promises',
        'module',
        'net',
        'os',
        'path',
        'path/posix',
        'path/win32',
        'perf_hooks',
        'process',
        'punycode',
        'querystring',
        'readline',
        'readline/promises',
        'repl',
        'stream',
        'stream/consumers',
        'stream/promises',
        'stream/web',
        'string_decoder',
        'sys',
        'timers',
        'timers/promises',
        'tls',
        'trace_events',
        'tty',
        'url',
        'util',
        'util/types',
        'v8',
        'vm',
        'wasi',
        'worker_threads',
        'zlib',

        // Node.js Built-ins (Explicit node: prefix)
        // CRITICAL: These must match the source code imports exactly
        'node:buffer',
        'node:crypto',
        'node:fs',
        'node:fs/promises',
        'node:path',
        'node:process',
        'node:stream',
        'node:timers/promises',
        'node:util',
        'node:os',
      ],
    },
  },
  plugins: [dts()],
});
